### ISSUE TITLE
A JavaScript error occured in the main process at app launch

### ISSUE THREAD

**Issue by m-beau** [denysdovhan/inboxer#36] opened 2018-03-09 17:05 UTC
Steps to reproduce:

- Open Inboxer 1.0.1 as a desktop app

The app doesn't open and this window pops up:
![screenshot from 2018-03-09 17-03-40](https://user-images.githubusercontent.com/25953361/37219613-e52049c4-23bb-11e8-8e9f-4e8768c5b82d.png)

Information about OS:
- Ubuntu 16.04

Thank you for your help!

**Comment by josmangarsal** [comment] 2018-03-13 10:04
Same in Ubuntu 17.10 with the .deb and .AppImage.

**Comment by darkoverlordofdata** [comment] 2018-03-19 04:36
Wow - I get exactly the same error in Windows 10. Now that is cross-platform :)

**Comment by m-beau** [comment] 2018-03-22 11:44
I figured out that this error actually occurs when I try to RE-open the app by hitting its icon while it is already active. It tries to open a second instance of the app, accompanied by the error message. The the already-opened instance remains open and accessible.

I guess the fix to do is to make sure that hitting the icon locked to launcher does not re-launch the app, but make the app window active instead.

**Comment by darkoverlordofdata** [comment] 2018-03-22 17:48
Thanks for the tip. I opened the notification tray, and sure enough, there is Inboxer. I just deleted the desktop icon, and it now works (Windows 10). This behavior is great, it's just not documented :)

**Comment by andredealmei** [comment] 2018-03-23 23:41
works only on click in icon on notification area of windows 10

**Comment by ags799** [comment] 2018-03-31 23:04
Same issue on macOS:

<img width="532" alt="screen shot 2018-03-31 at 5 56 57 pm" src="https://user-images.githubusercontent.com/2957581/38168269-2dd7ddd2-350d-11e8-98c2-664ef037e2ee.png">

Steps:
1. install the app from .dmg file
2. log into my 2 Google Accounts
3. open app preferences
3. uncheck the "unread badge" checkbox
4. note that the error dialog (pictured) appears
5. click "ok"
6. the error dialog disappears and another identical dialog appears
7. force quit the app
8. reopen the app
9. note that the error dialog (pictured) appears
10. click "ok"
11. the error dialog disappears and another identical dialog appears

<img width="698" alt="screen shot 2018-03-31 at 5 58 12 pm" src="https://user-images.githubusercontent.com/2957581/38168271-361e6ca4-350d-11e8-92d5-c7e60f35cecf.png">

**Comment by denysdovhan** [comment] 2018-04-14 15:12
Duplicate of #30

**Comment by denysdovhan** [comment] 2018-04-14 15:13
Duplicate of #29

**Comment by denysdovhan** [comment] 2018-04-14 15:13
Duplicate of #28

**Comment by denysdovhan** [comment] 2018-04-14 15:13
Duplicate of #9

**Comment by denysdovhan** [comment] 2018-04-14 15:28
Thanks for reporting! Should be fixed by #44. Thanks, @JohnnyBui!

Please, update to the version `v1.1.0` :pray:

**Comment by ags799** [comment] 2018-04-14 16:17
@denysdovhan I tried 1.1.0 and got the same error. Refer to my [previous comment](https://github.com/denysdovhan/inboxer/issues/36#issuecomment-377729657) for details.

**Comment by johnnybui** [comment] 2018-04-14 16:45
It's a different issue to the one on this thread @ags799. I will get into this soon. Should we keep this on this thread? @denysdovhan?

**Comment by denysdovhan** [comment] 2018-04-14 17:57
@JohnnyBui you can reopen this issue if needed.

**Comment by johnnybui** [comment] 2018-04-15 04:23
This issue should be fixed at my PR https://github.com/denysdovhan/inboxer/pull/45, @denysdovhan please check it.

**Closed as completed** 2018-04-16 13:54 UTC
Labels: bug, help wanted, good first issue
