### ISSUE TITLE
Cannot add newer accountes

### ISSUE THREAD

**Issue by fjrg76-com** [denysdovhan/inboxer#2] opened 2017-11-30 22:57 UTC
---
Inboxer 0.4.1
Electron 1.7.9
linux x64 4.10.0-40-generic

The "Add account" option doesn't do anything, so I cannot add my Hotmail account.

---
Linux Mint 18.2, Cinnamon, DEB package

**Comment by denysdovhan** [comment] 2017-12-02 00:12
First of all, Inbox by Gmail is made for Gmail. As far as I know, it does not work with other mail services. 

> The "Add account" option doesn't do anything

That's interesting. Can you, please, provide more information about your issue. I can't reproduce this right now.

**Comment by fjrg76-com** [comment] 2017-12-04 02:38
_First of all, Inbox by Gmail is made for Gmail. As far as I know, it does not work with other mail services._

Ok, then the name is misleading. Without being an english native speaker, I might say you'd probably have used: "Inbox for Gmail", 'cause you're not Gmail.

    The "Add account" option doesn't do anything

_That's interesting. Can you, please, provide more information about your issue. I can't reproduce this right now._

That's all information I have: It just do nothing when the "Add account" option is pressed. I'm also a programmer (C++) one, so I should look at the code myself.

LM 18.3 Cinnamon 64B, 4G RAM.

**Comment by oneguy** [comment] 2018-02-15 19:34
Hey @denysdovhan 

I've got the same issue. New Account menu item does not do anything. 

I install the app using brew cask.

How can I help you troubleshoot this?

**Comment by ClsoHC** [comment] 2018-11-18 02:11
Same issue.

New Account menu item does not do anything

**Comment by jmarino** [comment] 2019-03-29 14:55
Is this still an issue with latest release?

**Comment by denysdovhan** [comment] 2019-04-05 15:23
I want to close this project. Take a look at the explanation: #101

If you still need this project, please, fork the repo.

**Closed as completed by denysdovhan** 2019-04-05 15:23 UTC
Labels: question, wontfix
